site_name: IES4

repo_url: https://github.com/Bec-SU/IES4
repo_name: IES4
theme:
  icon:
    repo: fontawesome/brands/git-alt

nav:
  - Home: index.md
  - About: changelog.md

theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-4 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - IES HTML: ies4.html
  - IES Model: 
    - Model Overview: ./IES4Model/Overview.md
    - Relationships: 
      - Overview: ./IES4Model/Relationships/Overview.md
    
  - About:
    - Copyright & License: copyright.md
    - Release Notes: release-notes.md



plugins:
  - search
  - mermaid2:
      version: '11.0.0'
      arguments:
        theme: 'dark'
        themeVariables:
          primaryColor: '#BB2528'
          primaryTextColor: '#fff'
          primaryBorderColor: '#7C0000'
          lineColor: '#F8B229'
          secondaryColor: '#006100'
          tertiaryColor: '#fff'

markdown_extensions:
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid